### ISSUE TITLE
Expand Circle-CI Tutorial & add to Tech Stack

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-circleci#5]
_Sadly_, clients don't want to "_spend money_" on **Travis-CI** for their `private` repos ... 😢 💸 
So we have adopted Circle-CI for those projects ... 
@des-des kindly _started_ writing: https://github.com/dwyl/learn-circleci
however there is still a _lot_ of knowldege that remains [`tacit`](https://en.wikipedia.org/wiki/Tacit_knowledge) ... 😕 

# Tasks/Todo:

+ [x] Expand/complete the Circle-CI Tutorial
+ [x] explain that we _only_ use it for `private` projects (_because Travis-CI is bettererer_!)
+ [x] add section issues we have had to overcome while using Circle-CI (_share your learnings_!)
+ [ ] add to line to: https://github.com/dwyl/technology-stack see: https://github.com/dwyl/technology-stack/issues/25

**Comment by nelsonic** [comment]
I have summarised the process for CI/CD.
Deployment to a Dokku PaaS on DO. 
Closing.
